version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: bot_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./environments/.env.docker
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./environments/.env.docker
    depends_on:
      db:
        condition: service_healthy
    command: poetry run python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data: